#----------------------------------------------------------------------------
#   Dialog data and code block - do not modify this code by hand
#   Generated by LIBERO 2.11 on 29 Dec, 1996, 12:27.
#   Schema file used: lrschema.pl
#----------------------------------------------------------------------------

#-- Symbolic constants and event numbers ------------------------------------

$LR_defaults_state = 9;
$LR_STATE_after_init = 0;
$LR_STATE_expect_state_name = 1;
$LR_STATE_after_state = 2;
$LR_STATE_expect_event_name = 3;
$LR_STATE_expect_next_pointer = 4;
$LR_STATE_after_next_pointer = 5;
$LR_STATE_after_event = 6;
$LR_STATE_after_module_flag = 7;
$LR_STATE_after_module = 8;
$LR_STATE_defaults = 9;

$terminate_event = -1;                  # Halts the dialog
$LR_NULL_EVENT = -2;
$comment_event = 0;
$error_event = 1;
$event_number_event = 2;
$item_name_event = 3;
$module_flag_event = 4;
$next_pointer_event = 5;
$no_more_event = 6;
$ok_event = 7;
$option_event = 8;
$state_name_event = 9;
$state_name_term_event = 10;
$superstate_ref_event = 11;

#-- Standard subroutines used by dialog interpreter -------------------------

sub raise_exception {
    local ($event) = @_;
    $the_exception_event = $event;
    $exception_raised = 1;
}

sub LR_initialise {
    $LR_nextst = "";
    $LR_nextst .= "000000000000000100000000";
    $LR_nextst .= "000000020000000000020000";
    $LR_nextst .= "000003020000000000020202";
    $LR_nextst .= "000000040000000000000000";
    $LR_nextst .= "000000000705000000000000";
    $LR_nextst .= "000003060700050000020000";
    $LR_nextst .= "000003020700000000020000";
    $LR_nextst .= "000003080000070000020000";
    $LR_nextst .= "000003020700000000020000";
    $LR_nextst .= "090909090909090009090909";

    $LR_action = "";
    $LR_action .= "000000000000000100000000";
    $LR_action .= "000000030000000000020000";
    $LR_action .= "000005030000000000020604";
    $LR_action .= "000000070000000000000000";
    $LR_action .= "000000000908000000000000";
    $LR_action .= "000012100900130000110000";
    $LR_action .= "000015171600000000140000";
    $LR_action .= "000015180000190000140000";
    $LR_action .= "000005031600000000020000";
    $LR_action .= "222320202020240021202020";

    $LR_module = "";
    $LR_module .= "191718" . "00";
    $LR_module .= "041618" . "00";
    $LR_module .= "25041618" . "00";
    $LR_module .= "071618" . "00";
    $LR_module .= "231318" . "00";
    $LR_module .= "18" . "00";
    $LR_module .= "021518" . "00";
    $LR_module .= "1218" . "00";
    $LR_module .= "061418" . "00";
    $LR_module .= "0518" . "00";
    $LR_module .= "0601041618" . "00";
    $LR_module .= "0601231318" . "00";
    $LR_module .= "060111080924" . "00";
    $LR_module .= "01041618" . "00";
    $LR_module .= "01231318" . "00";
    $LR_module .= "1418" . "00";
    $LR_module .= "0125041618" . "00";
    $LR_module .= "0318" . "00";
    $LR_module .= "0111080924" . "00";
    $LR_module .= "10092224" . "00";
    $LR_module .= "2118" . "00";
    $LR_module .= "2018" . "00";
    $LR_module .= "092224" . "00";
    $LR_module .= "11080924" . "00";

    @LR_offset [1] = 0;
    @LR_offset [2] = 4;
    @LR_offset [3] = 8;
    @LR_offset [4] = 13;
    @LR_offset [5] = 17;
    @LR_offset [6] = 21;
    @LR_offset [7] = 23;
    @LR_offset [8] = 27;
    @LR_offset [9] = 30;
    @LR_offset [10] = 34;
    @LR_offset [11] = 37;
    @LR_offset [12] = 43;
    @LR_offset [13] = 49;
    @LR_offset [14] = 56;
    @LR_offset [15] = 61;
    @LR_offset [16] = 66;
    @LR_offset [17] = 69;
    @LR_offset [18] = 75;
    @LR_offset [19] = 78;
    @LR_offset [20] = 84;
    @LR_offset [21] = 89;
    @LR_offset [22] = 92;
    @LR_offset [23] = 95;
    @LR_offset [24] = 99;
}

#-- Dialog interpreter starts here ------------------------------------------

$LR_state = 0;                          #   First state is always 0
&LR_initialise;                         #   Initialise static strings
&initialise_the_program;
while ($the_next_event != $terminate_event)
  {
    $LR_event = $the_next_event;
    $LR_event < 0 || $LR_event >= 12 && die
        "State ", $LR_state,
        " - event ", $LR_event, " is out of range\n";
    $LR_index = ($LR_state * 12 + $LR_event) * 2;
    $LR_index = substr ($LR_action, $LR_index, 2);
    $LR_savest = $LR_state;

    #   If no action for this event, try the defaults state
    if ($LR_index == 0)
      {
        $LR_state = $LR_defaults_state;
        $LR_index = ($LR_state * 12 + $LR_event) * 2;
        $LR_index = substr ($LR_action, $LR_index, 2);
        $LR_index == 0 && die
            "State ", $LR_state,
            " - event ", $LR_event, " is not accepted\n";
      }
    $the_next_event = $LR_NULL_EVENT;
    $the_exception_event = $LR_NULL_EVENT;
    $exception_raised = 0;

    #   Execute module list for state transition, 0 indicates end of list
    $LR_vecptr = @LR_offset [$LR_index];
    $LR_modnbr = substr ($LR_module, $LR_vecptr * 2, 2);
    while ($LR_modnbr > 0 && !$exception_raised)
      {
        EXECUTE:                        #   Execute the module
          {
            $LR_modnbr == 1 && do { &attach_empty_module; last EXECUTE; };
            $LR_modnbr == 2 && do { &attach_new_event; last EXECUTE; };
            $LR_modnbr == 3 && do { &attach_new_module; last EXECUTE; };
            $LR_modnbr == 4 && do { &attach_new_state; last EXECUTE; };
            $LR_modnbr == 5 && do { &attach_next_state; last EXECUTE; };
            $LR_modnbr == 6 && do { &attach_same_next_state; last EXECUTE; };
            $LR_modnbr == 7 && do { &attach_uses_superstate; last EXECUTE; };
            $LR_modnbr == 8 && do { &build_source_file_name; last EXECUTE; };
            $LR_modnbr == 9 && do { &close_dialog_file; last EXECUTE; };
            $LR_modnbr == 10 && do { &display_unexpected_token; last EXECUTE; };
            $LR_modnbr == 11 && do { &expand_macro_constructs; last EXECUTE; };
            $LR_modnbr == 12 && do { &expect_event_definition; last EXECUTE; };
            $LR_modnbr == 13 && do { &expect_event_name; last EXECUTE; };
            $LR_modnbr == 14 && do { &expect_module_name; last EXECUTE; };
            $LR_modnbr == 15 && do { &expect_next_pointer; last EXECUTE; };
            $LR_modnbr == 16 && do { &expect_state_definition; last EXECUTE; };
            $LR_modnbr == 17 && do { &expect_state_name; last EXECUTE; };
            $LR_modnbr == 18 && do { &get_next_token; last EXECUTE; };
            $LR_modnbr == 19 && do { &open_dialog_file; last EXECUTE; };
            $LR_modnbr == 20 && do { &process_comment_value; last EXECUTE; };
            $LR_modnbr == 21 && do { &process_option_value; last EXECUTE; };
            $LR_modnbr == 22 && do { &return_error_feedback; last EXECUTE; };
            $LR_modnbr == 23 && do { &store_event_number; last EXECUTE; };
            $LR_modnbr == 24 && do { &terminate_the_program; last EXECUTE; };
            $LR_modnbr == 25 && do { &warning_on_state_name; last EXECUTE; };
          }
        $LR_vecptr++;
        $LR_modnbr = substr ($LR_module, $LR_vecptr * 2, 2);
      }

    #   Handle exception if any was raised
    if ($exception_raised)
      {
        $the_exception_event == $LR_NULL_EVENT ||
            ($LR_event = $the_exception_event);

        $the_next_event = $LR_event;
      }
    else
      {
        $LR_index = ($LR_state * 12 + $LR_event) * 2;
        $LR_state = substr ($LR_nextst, $LR_index, 2);
      }
    $LR_state = $LR_savest if ($LR_state == $LR_defaults_state);
    if ($the_next_event == $LR_NULL_EVENT)
      {
        &get_external_event;
        $the_next_event == $LR_NULL_EVENT && die
            "No event set after event ", $LR_event,
            " in state ", $LR_state, "\n";
      }
  }
1;                                      #   Return true value
